# Generated by Django 6.0.4 on 2026-04-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
