# Generated by Django 6.0.4 on 2026-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bankaccount_date_serial_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
