# Generated by Django 4.1 on 2022-09-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.GenericIPAddressField(null=True, protocol='ipv4'),
        ),
    ]
