# Generated by Django 4.1 on 2022-09-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['id']},
        ),
    ]
